site_name: My Project Docs
theme:
  name: material

nav:
  - Home: index.md
  - About: about.md
  - Installation: installation.md
  # - Usage: usage.md
  # - Configuration: configuration.md

repo_url: https://github.com/username/my-repo