name: Check Directory and Wait for Approval

on:
  pull_request:
    paths:
      - 'tf/**' # Only trigger if files in this directory change

jobs:
  check-directory-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if directory has changed
        id: check_changes
        run: |
          # Get list of changed files in the PR
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)

          # Check if files in the target directory are among the changed files
          if echo "$CHANGED_FILES" | grep -q '^tf/'; then
            echo "directory_changed=true" >> $GITHUB_ENV
          else
            echo "directory_changed=false" >> $GITHUB_ENV
          fi

  approval:
    needs: check-directory-changes
    if: env.directory_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Wait for approval
        uses: rishabh3112/gh-action-await-approval@v1
        with:
          approver: 'julenbadiola'
          message: 'Please review and approve changes in tf directory.'
