name: Run Python Tests, SonarQube Check, and Deploy with Terraform

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
  pull_request:
  # Allow manual triggering
  workflow_dispatch:

env:
  ENVIRONMENT: 'production'
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo "Github ref is: ${{ github.base_ref }}"

  python-tests:
    uses: axprueba/workflows/.github/workflows/run-python-tests.yml@master
    with:
      environment: ${{ github.base_ref }}
      python-version: '3.9'


  sonar-run:
    # needs: python-tests
    uses: axprueba/workflows/.github/workflows/run-sonar-python.yml@master
    with:
      environment: ${{ github.base_ref }}
      sonar-project-key: 'example-app'
      python-version: '3.9'
      tests-command: 'coverage run -m pytest && coverage xml -o coverage.xml'
      check-result: true

  # deploy-with-terraform:
  #   needs: sonar-run
  #   uses: axprueba/workflows/.github/workflows/run-deploy-with-terraform.yml@master
  #   with:
  #     terraform-version: '1.0.11'  # Specify the version
  #     environment: 'production'    # Specify the deployment environment
  #   secrets:
  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
