name: Run Python Tests, SonarQube Check, and Deploy with Terraform

on:
  push:
    branches:
      - master
  pull_request:
  # allow manual triggering
  workflow_dispatch:

jobs:
  # python-tests:
  #   uses: julenbadiola/workflows/.github/workflows/run-python-tests.yml@master
  #   with:
  #     python-version: '3.9'

  sonarqube-check:
    # needs: python-tests
    uses: julenbadiola/workflows/.github/workflows/run-sonarqube-python.yml@master
    with:
      sonarqube-project-key: 'example-app'
      python-version: '3.9'
      tests-command: 'coverage run -m pytest && coverage xml -o coverage.xml' 
    secrets:
      SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
      SONARQUBE_HOST_URL: ${{ secrets.SONARQUBE_HOST_URL }}

  deploy-with-terraform:
    needs: sonarqube-check
    uses: julenbadiola/workflows/.github/workflows/run-deploy-with-terraform.yml@master
    with:
      terraform-version: '1.0.11'  # Specify the version
      environment: 'production'    # Specify the deployment environment
    # secrets:
    #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
