name: Run Python Tests, SonarQube Check, and Deploy with Terraform

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
  pull_request:
  workflow_dispatch:

jobs:
  set-environment:
    runs-on: ubuntu-latest
    outputs:
      ENVIRONMENT: ${{ steps.set-env.outputs.ENVIRONMENT }}
    steps:
      - name: Determine Environment
        id: set-env
        run: |
          if [[ "$GITHUB_REF_NAME" == "main" ]]; then
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
            echo "ENVIRONMENT=production" >> $GITHUB_OUTPUT
          elif [[ "$GITHUB_REF_NAME" == "qa" ]]; then
            echo "ENVIRONMENT=qa" >> $GITHUB_ENV
            echo "ENVIRONMENT=qa" >> $GITHUB_OUTPUT
          else
            echo "ENVIRONMENT=develop" >> $GITHUB_ENV
            echo "ENVIRONMENT=develop" >> $GITHUB_OUTPUT
          fi

  debug:
    needs: set-environment
    runs-on: ubuntu-latest
    steps:
      - name: Debug Output
        run: echo "Resolved Environment ${{ needs.set-environment.outputs.ENVIRONMENT }}"

  python-tests:
    needs: set-environment
    uses: axprueba/workflows/.github/workflows/run-python-tests.yml@master
    with:
      python-version: '3.9'
    secrets: inherit

  sonar-run:
    needs: [set-environment, python-tests]
    uses: axprueba/workflows/.github/workflows/run-sonar-python.yml@master
    with:
      sonar-project-key: ${{ github.event.repository.name }}-${{ github.ref_name }}
      python-version: '3.9'
      tests-command: 'coverage run -m pytest && coverage xml -o coverage.xml'
      check-result: true
    secrets: inherit

  deploy-with-terraform:
    needs: [set-environment, sonar-run]
    uses: axprueba/workflows/.github/workflows/run-deploy-with-terraform.yml@master
    with:
      terraform-version: '1.0.11'
      environment: ${{ needs.set-environment.outputs.ENVIRONMENT }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
